name: macOS

on: [push]

jobs:
  build-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: install-build-dependencies
        run: brew install eigen qt@5
      - name: submodule
        run: git submodule update --init --recursive
      - name: build
        run: |
          cmake .
          make
