name: Ubuntu

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install-build-dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libeigen3-dev qt5-default
      - name: submodule
        run: git submodule update --init --recursive
      - name: build
        run: |
          cmake .
          make
